### ISSUE TITLE
Oak Log Translation is Wrong

### ISSUE THREAD

**Issue by DarkArc** [Phoenix616/IDConverter#3]
https://github.com/Phoenix616/IDConverter/blob/master/mappings/src/main/java/de/themoep/idconverter/IdMappings.java#L63-L64

At least for MC 1.12.2, oak logs are `17:0`, and spruce are `17:1`.

**Comment by DarkArc** [comment]
Worked around this with the following "overrides" https://github.com/packet-loss-gaming/Grindstone/commit/b23a48346d4e8215743eb2bb3da5d82a74bf8b68#diff-bf74fd5b237af297c62c95dfa066e92fR55-R60

Thanks so much for the library! Saved me a lot of pain overall.

**Comment by Phoenix616** [comment]
Thank you for pointing that out!
